// export const questions = 
globalThis.questions = 
{
    "Quadratic Formula": "x = \\dfrac{-b\\pm\\sqrt{b^2-4ac}}{2a}",
    "Pythagorean Theorem": "c = \\sqrt{a^2+b^2}",
    "Sum of first \\(n\\) Squares": "\\sum_{i=1}^n i^2 = \\frac{n(n+1)(2n+1)}{6}",
    "Law of Cosines": "c^2 = a^2 + b^2 - 2ab \\cos \\angle C",
    "Legendre's formula": "\\nu_p(n!) = \\sum_{i = 1}^{\\infty} \\left \\lfloor \\dfrac{n}{p^i} \\right \\rfloor",
    "Euler's Identity": "e^{\\pi i} + 1 = 0",
    "Euler's Lesser-Known Identity": "\\lceil e \\rceil - \\lfloor \\pi \\rfloor = 0",
    "Normal Distribution": "\\Phi(x) = \\frac{1}{\\sigma \\sqrt{2\\pi}} e^{-\\frac{(x - \\mu)^2}{2\\sigma^2}}",
    "Fourier Transform": "\\hat{f}(\\omega) = \\int_{-\\infty}^\\infty f(x) e^{-2\\pi i x \\omega} \\mathrm dx",
    "Wave Equation": "\\frac{\\partial^2u}{\\partial t^2} = c^2 \\frac{\\partial^2 u}{\\partial x^2}",
    "Navier-Stokes Equation": "\\rho \\left ( \\frac{\\partial \\mathbf{v}}{\\partial t} + \\mathbf{v} \\cdot \\nabla \\mathbf{v} \\right) = - \\nabla p + \\nabla \\cdot \\mathbf{T} + \\mathbf{f}",
    "Schrodinger's Equation": "i\\hbar\\frac{\\partial}{\\partial t} \\Psi = H \\Psi",
    "Black-Scholes Equation": "\\frac{\\partial V}{\\partial t} + \\frac{1}{2} \\sigma^2 S^2 \\frac{\\partial^2V}{\\partial S^2} + rS \\frac{\\partial V}{\\partial S} - rV = 0",
    "Relativity": "E=mc^2",
    "Chaos Theory": "x_{t+1} = k x_t (1 - x_t)",
    "Definition of the Derivative": "\\frac{\\mathrm df}{\\mathrm dx} = \\lim_{h \\to 0} \\frac{f(x + h) - f(x)}{h}",
    "Euler's Formula for Polyhedra": "V - E + F = 2",
    "Gravitation": "F = \\frac{Gm_1m_2}{d^2}",
    "AM-GM": "\\frac{x_1 + x_2 + \\cdots + x_n}{n} \\ge \\sqrt[n]{x_1 \\cdot x_2 \\cdots x_n}",
    "Stirling's Approximation": "n! \\approx \\sqrt{2\\pi n} \\left ( \\frac{n}{e}\\right )^n",
    "Stokes' Theorem": "\\iint_S \\nabla \\times \\mathbf{F} \\cdot \\mathrm d\\mathbf{S} = \\oint_\\Gamma \\mathbf{F} \\cdot \\mathrm d \\mathbf{\\Gamma} ",
    "Divergence Theorem": "\\iiint_V (\\nabla \\cdot \\mathbf{F}) \\mathrm dV = \\oiint_S (\\mathbf{F} \\cdot \\mathbf{n}) \\mathrm dS",
    "Cauchy-Schwarz Inequality": "|\\langle \\mathbf{u}, \\mathbf{v} \\rangle|^2 \\le \\langle \\mathbf{u}, \\mathbf{u} \\rangle \\cdot \\langle \\mathbf{v} , \\mathbf{v} \\rangle",
    "Area of a Circle": "A = \\pi r^2",
    "Definition of \\(\\tau\\)": "\\tau = 2\\pi",
    "Sophie Germain Identity": "a^4 + 4b^4 = (a^2 + 2ab + 2b^2)(a^2 -2ab + 2b^2)",
    "Pascal's Identity": "\\binom{n}{k} = \\binom{n-1}{k} + \\binom{n-1}{k-1}",
    "Hockey-stick Identity": "\\sum_{i=r}^n \\binom{i}{r} = \\binom{n+1}{r+1}",
    "Vandermonde's Identity": "\\binom{m + n}{r} = \\sum_{k = 0}^r \\binom{m}{k} \\binom{n}{r-k}",
    "Combinations": "\\binom{n}{k} = \\frac{n!}{k!(n-k)!}",
    "Heine's Identity": "\\frac{1}{\\sqrt{z - \\cos \\psi}} = \\frac{\\sqrt{2}}{\\pi} \\sum_{m = -\\infty}^\\infty Q_{m - \\frac{1}{2}}(z) e^{im\\psi}",
    "Binomial identity": "(x + y)^n = \\sum_{k=0}^n \\binom{n}{k} x^{n-k} y^k",
    "Hermite's Identity": "\\sum_{k=0}^{n-1} \\left \\lfloor x + \\frac{k}{n} \\right \\rfloor = \\lfloor nx \\rfloor",
    "Matrix Determinant Lemma": "\\det (\\mathbf{A} + \\mathbf{u}\\mathbf{v}^{\\intercal}) = (1 + \\mathbf{v}^\\intercal \\mathbf{A}^{-1} \\mathbf{u}) \\det (\\mathbf{A})",
    "Euler Product of the Riemann-Zeta function": "\\zeta(s) = \\sum_{n=1}^\\infty \\frac{1}{n^s} = \\prod_{p \\in \\mathbb{P}} \\frac{1}{1 - p^{-s}}",
    "Irrationality of the Square Root of 2": "\\sqrt{2} \\notin \\mathbb{Q}",
    "Heron's Formula": "[\\triangle ABC] = \\sqrt{s(s-a)(s-b)(s-c)}",
    "Heisenberg's Uncertainty Principle": "\\Delta x \\Delta p \\approx \\hbar",
    "Continued Fraction for \\(\\pi/2\\)": "\\frac{\\pi}{2} = 1 + \\frac{1}{1 + \\frac{1}{\\frac{1}{2} + \\frac{1}{\\frac{1}{3} + \\frac{1}{\\frac{1}{4} + \\ddots}}}}",
    "Sophomore's Dream": "\\int_0^1 x^{-x} \\mathrm dx = \\sum_{n=1}^\\infty n^{-n}",
    "Identity involving \\(\\pi\\) and \\(e\\)": "\\prod_{n=2}^\\infty e \\left (1 - \\frac{1}{n^2} \\right)^{n^2} = \\frac{\\pi}{e \\sqrt{e}}",
    "Representation of the Golden Ratio": "\\phi = \\sqrt{1 + \\sqrt{1 + \\sqrt{1 + \\sqrt{1 + \\cdots}}}}",
    "The Sum of all Positive Integers": "\\sum_{n = 1}^\\infty n = -\\frac{1}{12}",
    "Inverse of a complex number": "z^{-1} = \\frac{\\bar{z}}{|z|^2}, \\forall z \\neq 0",
    "Definition of Convolution": "(f * g)(t) = \\int_{-\\infty}^\\infty f(\\tau) g(t - \\tau) \\mathrm d\\tau",
    "Definition of the Kronecker Delta function": "\\delta_{i,j} = \\begin{cases} 0 & i \\neq j \\\\ 1 & i = j \\end{cases}",
    "Bayes' Theorem": "P(A | B) = \\frac{P(B|A)P(A)}{P(B)}",
    "Probability Density Function of the Student's \\(t\\)-distribution": "f(t) = \\frac{\\Gamma \\left ( \\frac{\\nu + 1}{2} \\right )}{\\sqrt{\\nu \\pi} \\Gamma \\left ( \\frac{\\nu}{2}\\right)} \\left ( 1 + \\frac{t^2}{\\nu} \\right) ^{- \\frac{\\nu + 1}{2}}",
    "De Morgan's laws": "\\neg (P \\wedge Q ) \\vdash (\\neg P) \\vee (\\neg Q)",
    "Principle of Inclusion-Exclusion": "|A \\cup B| = |A| + |B| - |A \\cap B|",
    "General Principle of Inclusion-Exclusion": "\\left | \\bigcup_{i = 1}^n A_i \\right | = \\sum_{\\emptyset \\neq J \\subseteq \\{1, \\dots, n\\}} (-1)^{|J| + 1} \\left | \\bigcap_{j \\in J} A_j \\right |",
    "Determinant of a \\(2 \\times 2\\) matrix": "\\det \\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix} = ad - bc",
    "Sawtooth Function": "S(x) = \\begin{cases} x - \\lfloor x \\rfloor - 1/2 & x \\in \\mathbb{R} \\setminus \\mathbb{Z} \\\\ 0 & x \\in \\mathbb{Z} \\end{cases}",
    "Definition of Graham's Number": "g_n = \\begin{cases} 3 \\uparrow \\uparrow \\uparrow \\uparrow 3 & n = 1 \\\\ 3 \\uparrow^{g_{n-1}} 3 & n \\ge 2,n \\in \\mathbb{N} \\end{cases}",
    "Burnside's Lemma": "|X/G| = \\frac{1}{|G|} \\sum_{g \\in G} |X^g|",
    "Continuum Hypothesis": "\\aleph_0 = |\\mathbb{N}|, \\mathfrak{c} = |\\mathbb{R}| \\\\ \\nexists A : \\aleph_0 < |A| < \\mathfrak{c}",
    "Spectral Decomposition": "A = \\begin{pmatrix} | & | & & | \\\\ \\mathbf v_1 & \\mathbf v_2 & \\cdots & \\mathbf v_n \\\\ | & | & & | \\end{pmatrix} \\begin{pmatrix} \\lambda_1 & & & \\\\ & \\lambda_2 & & \\\\ & & \\ddots & \\\\ & & & \\lambda_n \\end{pmatrix} \\begin{pmatrix} | & | & & | \\\\ \\mathbf v_1 & \\mathbf v_2 & \\cdots & \\mathbf v_n \\\\ | & | & & | \\end{pmatrix} ^ {-1}",
    "Pythagorean Identity": "\\sin^2 \\theta + \\cos^2 \\theta = 1",
    "Double Angle for sin": "\\sin(2\\theta) = 2\\sin(\\theta)\\cos(\\theta)",
    "Double Angle for cos": "\\cos(2\\theta) = \\cos^2(\\theta) - \\sin^2(\\theta)",
    "Fermat's Last Theorem": "\\nexists \\{x,y,z,n\\} \\in \\mathbb{N}, n > 2 : x^n + y^n = z^n",
    "Fermat's Little Theorem": "a^p \\equiv a \\pmod{p}",
    "Euler's Theorem": "\\gcd(a, n) = 1 \\implies a^{\\varphi(n)} \\equiv 1 \\pmod{n}",
    "QM-AM-GM-HM Inequality over 3 variables": "\\sqrt{\\frac{a^2 + b^2 + c^2}{3}} \\ge \\frac{a + b + c}{3} \\ge \\sqrt[3]{abc} \\ge \\frac{3}{\\frac{1}{a} + \\frac{1}{b} + \\frac{1}{c}}",
    "Extended Law of Sines": "\\frac{a}{\\sin \\angle A} = \\frac{b}{\\sin \\angle B} = \\frac{c}{\\sin \\angle C} = 2R",
    "Integration by Parts": "\\int u\\mathrm dv = uv - \\int v \\mathrm du",
    "Definition of Perfect Numbers": "\\left \\{ n : \\sum_{d | n}^{d<n} d  = n\\right \\}",
    "Gaussian Integral": "\\int_{-\\infty}^\\infty e^{-x^2} \\mathrm dx = \\sqrt{\\int_{-\\infty}^\\infty \\int_{-\\infty}^\\infty  e^{-x^2 - y^2} \\mathrm dx\\mathrm dy} = \\sqrt{\\int_0^{2\\pi} \\int_0^\\infty e^{-r^2}r\\mathrm dr\\mathrm d\\theta } = \\sqrt{\\pi}",
    "Definition of an Integral": "\\int_a^b f(x) \\mathrm dx = \\lim_{k \\to \\infty} \\left ( (b-a) \\sum_{i = 1}^{k} \\frac{f(a + i\\frac{b-a}{k})}{k} \\right )",
    "Quantum Fourier transform": "|x\\rangle \\mapsto \\frac{1}{\\sqrt{N}} \\sum_{k = 0}^{N-1} \\omega_x^k |k\\rangle",
    "Recursive definition of the Hadamard transform": "H_m = \\begin{cases} 1 & m = 0 \\\\ \\frac{1}{\\sqrt{2}}\\begin{pmatrix} H_{m-1} & H_{m-1} \\\\ H_{m-1} & -H_{m-1}\\end{pmatrix} & m > 0\\end{cases}",
    "Wigner Transform of the Density Matrix": "W(x,p) = \\frac{1}{\\pi \\hbar} \\int_{-\\infty}^\\infty \\langle x + y | \\hat{\\rho} | x - y \\rangle e^{-2ipy/\\hbar} \\mathrm dy",
    "Imaginary numbers": "i^2 = -1",
    "Sum of Cubes": "a^3 + b^3 = (a+b)(a^2 - ab + b^2)",
    "RSA Decryption Algorithm": "m = c^{e^{-1}\\bmod \\phi(n)} \\pmod n",
    "Contraposition": "(p \\implies q) \\iff (\\neg q \\implies \\neg p)",
    "Equation of a spring": "m \\ddot{x} = -kx",
    "Sum of reciprocals of partial sums of \\(\\ \\mathbb{N}\\)": "\\sum_{i = 2}^\\infty \\frac{1}{\\sum_{j = 1}^i j} = 1",
    "Binet's Formula": "F_n = \\frac{1}{\\sqrt{5}} \\left ( \\varphi^n  - \\frac{(-1)^n}{\\varphi^n}\\right )",
    "Sum of first \\(n\\) Cubes": "\\sum_{k = 0}^n k^3 = \\left ( \\sum_{k = 0}^n k\\right )^2",
    "The Basel Problem": "\\sum_{n = 1}^\\infty \\dfrac{1}{n^2} = \\dfrac{\\pi^2}{6}",
    "Root Mean Square": "f_{\\text{rms}} = \\sqrt{\\frac{1}{T_2 - T_1} \\int_{T_1}^{T_2} [f(t)]^2 \\mathrm dt}",
    "The Harmonic Series": "\\sum^\\infty_{n=1} \\frac{1}{n} = \\infty",
    "Tupper's Self-Referential Formula": "\\frac{1}{2}<\\left\\lfloor\\bmod\\left(\\left\\lfloor\\frac{y}{17}\\right\\rfloor 2^{-17\\lfloor x \\rfloor - \\bmod(\\lfloor y \\rfloor,17)},2\\right)\\right\\rfloor",
    "H\\(\\ddot\\textbf{o}\\)lder's Inequality": "\\left(\\sum_{i = 1}^n a_i\\right)^p\\left(\\sum_{i = 1}^n b_i\\right)^q \\ge \\left(\\sum_{i = 1}^n \\sqrt[p+q]{a_i^p b_i^q}\\right)^{p+q}",
    "Rearrangement Inequality": "a_1 \\le a_2 \\le \\cdots \\le a_n, b_1 \\le b_2 \\le \\cdots \\le b_n \\implies \\sum_{i=1}^n a_ib_i \\ge \\sum_{i=1}^n a_{\\sigma(i)}b_i \\ge \\sum_{i=1}^n a_{n+1-i}b_i",
    "Power Mean": "M_r(x_1,x_2,\\dots,x_n) = \\begin{cases} \\left(\\frac{1}{n}\\sum_{i=1}^n x_i^r\\right)^{1/r} & r \\ne 0 \\\\ \\sqrt[n]{\\prod_{i=1}^n x_i} & r = 0 \\end{cases}",
    "Law of Tangents": "\\frac{a-b}{a+b} = \\frac{\\tan\\left(\\frac{\\angle A - \\angle B}{2}\\right)}{\\tan\\left(\\frac{\\angle A + \\angle B}{2}\\right)}",
    "Euler's Arctangent Identity": "\\tan^{-1} \\left(\\frac{1}{x}\\right) =  \\tan^{-1} \\left(\\frac{1}{x+y}\\right) + \\tan^{-1}\\left(\\frac{y}{x^2 + xy + 1}\\right)",
    "The Dirichlet Convolution": "(f \\ast g)(n) = \\sum_{d | n} f(d)g\\left(\\frac{n}{d}\\right)",
    "Sum of a Row of Pascal's Triangle": "\\binom{n}{0} + \\binom{n}{1} + \\binom{n}{2} + \\cdots + \\binom{n}{n} = 2^n",
    "Alternating Harmonic Series": "1 - \\frac 12 + \\frac 13 - \\frac 14 + \\frac 15 - \\cdots = \\ln 2",
    "Definitions of Catalan's Constant": "G = \\beta(2) = \\sum_{k=0}^\\infty \\frac{(-1)^k}{(2k+1)^2} = \\iint_{[0,1]^2} \\frac{\\mathrm dx \\mathrm dy}{1 + x^2 y^2}",
    "Series Representation of Ap\\(\\acute\\textbf{e}\\)ry's Constant": "\\zeta(3) = \\frac{5}{2} \\sum_{n=1}^\\infty \\frac{(-1)^{n-1}}{n^3 \\binom{2n}{n}}",
    "Definition of the Euler-Mascheroni Constant": "\\gamma = \\lim_{n \\to \\infty} \\left(\\sum_{k=1}^n \\frac{1}{k} - \\ln n \\right) = \\int_1^\\infty  \\left(\\frac{1}{\\lfloor x \\rfloor } - \\frac{1}{x} \\right) \\mathrm dx",
    "Mertens' therorem": "\\prod_{p \\in \\mathbb P}^n \\left(1-\\frac 1 p \\right)\\sim \\frac{e^{-\\gamma}}{\\log n}",
    "Green's First Identity": "\\int_{\\Omega} (\\psi \\Delta \\varphi + \\nabla \\psi \\cdot \\nabla \\varphi) \\mathrm dV = \\oint_{\\partial \\Omega} \\psi(\\nabla \\varphi \\cdot \\mathbf{n}) \\mathrm dS",
    "Cauchy-Riemann Equations": "\\frac{\\partial u}{\\partial x} = \\frac{\\partial v}{\\partial y}, \\frac{\\partial u}{\\partial y} = -\\frac{\\partial v}{\\partial x}",
    "Cauchy's Integral Formula": "f(z_0) = \\frac{1}{2\\pi i}\\oint_{\\Gamma} \\frac{f(z)}{z-z_0} \\mathrm{d}z",
    "Cauchy's Differentiation Formula": "f^{(n)}(a) = \\frac{n!}{2\\pi i} \\oint_{\\gamma} \\frac{f(z)}{(z-a)^{n+1}} \\mathrm{d}z",
    "Functional Equation for the Riemann-Zeta Function": "\\pi^{-s/2}\\Gamma\\left(\\frac{s}{2}\\right)\\zeta(s) = \\pi^{-(1-s)/2}\\Gamma\\left(\\frac{1-s}{2}\\right)\\zeta(1-s)",
    "Well-ordering Principle": "\\forall M(M\\subset \\mathbb N \\wedge M \\ne \\emptyset \\implies \\exists m_0 [ m_0 \\in M \\wedge \\forall n (n \\in M \\implies m \\le n)])",
    "Asymptotic Formula for the Dirichlet Divisor Function": "\\sum_{n \\leq x} \\tau(n) = x \\log x + (2\\gamma -1)x + O(\\sqrt{x})",
    "Prime Number Theorem": "\\pi(x) \\sim \\frac{x}{\\log x}",
    "Cumulative Distribution Function of the Gaussian Distribution": "\\Phi(x) = \\frac{1}{\\sqrt{2\\pi}}\\int_{-\\infty}^x e^{-t^2/2} \\mathrm{d}t",
    "Chernoff Bound": "\\mathbb{P}(X \\ge t) \\leq \\frac{\\mathbb{E}[e^{\\lambda X}]}{e^{\\lambda t}}",
    "Union Bound": "\\mathbb{P}\\left(\\bigcup_{i=1}^n X_i\\right) \\leq \\sum_{i=1}^n \\mathbb{P}(X_i)",
    "Law of Total Probability": "\\mathbb{P}(A) = \\sum_{i=1}^n \\mathbb{P}(A| B_i)\\mathbb{P}(B_i)",
    "Linear Least Squares Estimator": "L[X|Y] = \\mathbb{E}[X] + \\frac{\\mathrm{cov}(X,Y)}{\\mathrm{var}(Y)} (Y-\\mathbb{E}[Y])",
    "Rademacher Complexity": "\\mathcal{R}_n(\\mathcal{F}) = \\mathbb{E}_{\\varepsilon}\\left[\\sup_{f \\in \\mathcal{F}}\\frac{1}{n}\\sum_{i=1}^{n}\\varepsilon_if(x_i) \\right ]",
    "Definition of the Dilogarithm": "\\mathrm{Li}_2(z) = -\\int_0^z \\frac{\\log(1-t)}{t}\\mathrm{d}t, z \\in \\mathbb C",
    "Leibniz's Determinant Formula": "\\det(A)=\\sum_{\\sigma\\in S_n} \\epsilon(\\sigma)\\prod_{i=1}^n A_{i,\\sigma(i)}",
    "Euler-Lagrange Equations": "\\frac{\\partial L}{\\partial q_i}=\\frac{\\mathrm d}{\\mathrm dt}\\frac{\\partial L}{\\partial \\dot{q_i}}",
    "Definition of the Euler Totient Function": "\\varphi(n)=|\\{k\\in\\mathbb{N}_{\\leq n}|\\gcd(k,n)=1\\}|=n\\prod_{p|n}\\left(1-\\frac1p\\right)",
    "Sum of Divisors": "\\sigma(n)=\\sum_{d|n} d = \\prod_{p^a||n}\\left(\\frac{p^{a+1}-1}{p-1}\\right)",
    "Einstein Field Equations": "G_{\\mu\\nu}+\\Lambda g_{\\mu\\nu} = \\frac{8\\pi G}{c^4}T_{\\mu\\nu}",
    "Second Fundamental Theorem of Calculus": "\\int_a^b f(x)\\mathrm{d}x=[F(x)]_{a}^{b}=F(b)-F(a)",
    "Abel's Summation Formula": "\\sum_{x < n \\leq y} a(n)f(n) = A(y)f(y) - A(x)f(x) - \\int_x^y A(t)f'(t) \\mathrm dt",
    "Lagrange's Theorem": "(G:H) = \\frac{|G|}{|H|}",
    "Catalan Numbers": "C_n = \\sum_{k=1}^{n-1} C_kC_{n-k-1} = \\frac{1}{n+1}\\binom{2n}{n}",
    "Ising Model Hamiltonian": "H(\\sigma )=-\\sum _{\\langle i,j\\rangle }J_{ij}\\sigma _{i}\\sigma _{j}-\\mu \\sum _{j}h_{j}\\sigma _{j}",
    "Borwein Integral": "\\int_0^\\infty \\frac{\\sin(x)}{x}\\frac{\\sin(x/3)}{x/3}\\cdots\\frac{\\sin(x/13)}{x/13}\\mathrm dx=\\frac{\\pi}{2}",
    "Wigner Semicircle Distribution": "f(x)=\\begin{cases}{2 \\over \\pi R^2}\\sqrt{R^2-x^2}&-R\\le x\\le R\\\\ 0&|x|>R\\end{cases}",
    "Parseval Gutzmer Formula": "f(z)=\\sum_{k=0}^\\infty a_kz^k\\implies \\frac{1}{2\\pi}\\int_0^{2\\pi}|f(re^{i\\theta})|^2\\mathrm d\\theta=\\sum_{k=0}^\\infty |a_kr^k|^2",
    "Fubini's Theorem": "\\int _{X}\\left(\\int _{Y}f(x,y) \\mathrm dy\\right) \\mathrm dx=\\int _{Y}\\left(\\int _{X}f(x,y) \\mathrm dx\\right) \\mathrm dy=\\int _{{X\\times Y}}f(x,y)\\mathrm d(x,y)",
    "Coarea Formula": "\\int _{\\Omega }g(x)|\\nabla u(x)|\\mathrm dx=\\int _{\\mathbb {R} }\\left(\\int _{u^{-1}(t)}g(x)\\mathrm dH_{n-1}(x)\\right)\\mathrm dt",
    "Equation of a Torus": "(\\sqrt{x^2 + y^2} - R)^2 + z^2 = r",
    "Ampère-Maxwell law": "\\nabla \\times \\mathbf{B} = \\mu_0\\left(\\mathbf{J} + \\varepsilon_0 \\frac{\\partial \\mathbf{E}}{\\partial t}\\right)",
    "Gauss's Flux Theorem (differential form)": "\\nabla \\cdot \\mathbf{E} = \\frac{\\rho}{\\varepsilon_0}",
    "Gauss's law for Magnetism": "\\nabla \\cdot \\mathbf{B} = 0",
    "Maxwell–Faraday equation": "\\nabla \\times \\mathbf{E} = -\\frac{\\partial \\mathbf{B}}{\\partial t}",
    "Eigenvalue Formula": "\\det(\\mathbf{A} - \\lambda \\mathbf{I}) = 0",
    "Collatz Function": "f(n) = \\begin{cases} n/2 & n \\equiv 0 \\pmod 2 \\\\ 3n + 1 & n \\equiv 1 \\pmod 2 \\end{cases}",
    "Gamma Function": "\\Gamma(z) = \\int_0^\\infty x^{z - 1}e^{-x} \\mathrm dx",
    "Laplace Transform": "\\mathcal{L}\\{f\\}(s) = \\int_0^\\infty f(t) e^{-st} \\mathrm dt",
    "Taylor Series": "f(x) = \\sum_{n = 0}^\\infty \\frac{f^{(n)}(a)}{n!} (x - a)^n",
    "Quaternion Multiplication Formula": "\\mathbf i^2 = \\mathbf j^2 = \\mathbf k^2 = \\mathbf i\\mathbf j\\mathbf k = -1",
    "General Solution to First-Order Linear Differential Equations": "y = e^{-\\int P(x) \\mathrm dx} \\int Q(x) e^{\\int P(x) \\mathrm dx} \\mathrm dx + Ce^{-\\int P(x)\\mathrm dx}",
    "Fibonacci Binomial Coefficients Identity": "F_{n+1}=\\binom n 0 +\\binom {n-1}1+\\binom{n-2}2+\\cdots + \\binom{n - \\lfloor n/2 \\rfloor }{\\lfloor n/2 \\rfloor}",
    "Bellman Optimality Equation": "V^{\\pi*}(s)=  \\max_a \\{ {R(s,a) + \\gamma \\sum_{s'} P(s'|s,a) V^{\\pi*}(s')} \\}",
    "Definition of a Well-founded Relation": "(\\forall S \\subseteq X) [S \\neq \\emptyset \\implies (\\exists m \\in S) (\\forall s \\in S) \\lnot(sRm)]",
    "Estimation Lemma": "\\left|\\int_\\gamma f(z) \\mathrm dz\\right|\\leq L(\\gamma) \\sup_\\gamma | f |",
    "Chaitin's Constant": "\\Omega_{F} = \\sum_{p \\in P_F} 2^{-|p|}",
    "Defintion of the Quasi-Stationary Distribution": "\\forall B \\in \\mathcal{B}(\\mathcal{X}^a), \\forall t \\ge 0, P_\\nu(Y_t\\in B, T > t) = \\nu(B)P_\\nu(T>t)",
    "Addition of Sound Levels in Decibels": "L_{ab} = 10\\log_{10}\\left(10^{L_a/10}+10^{L_b/10}\\right)",
    "Fast-Growing Hierarchy": "f_\\alpha(n)=\\begin{cases}n+1&\\alpha=0\\\\f_\\beta(n)&\\alpha=\\beta+1\\\\f_{\\alpha[n]}(n)&\\text{else}\\end{cases}",
    "Feigenbaum-Cvitanović Functional Equation": "g(g(x)) = - \\frac{1}{\\alpha} g(\\alpha x)",
    "Dirac Equation": "i \\hbar \\gamma^\\mu \\partial_\\mu \\psi - mc \\psi = 0 ",
    "Feynman's Trick": "\\int_0^\\pi\\ln(1-2\\alpha\\cos x+\\alpha^2) \\mathrm dx=2\\pi\\ln|\\alpha|",
    "Lorentz Factor": "\\gamma = \\frac{1}{\\sqrt{1-\\frac{v^{2}}{c^{2}}}}",
    "Time Dilation": "\\Delta t=\\frac{\\Delta t_{0}}{\\sqrt{1-\\frac{v^{2}}{c^{2}}}}",
    "Gauss's Flux Theorem (integral form)": "\\oiint_S\\mathbf{E}\\cdot\\mathrm{d}\\mathbf{A}=\\frac{Q}{\\varepsilon_{0}}",
    "Doppler Effect": "\\frac{f_{o}}{f_{s}} = \\frac{\\lambda_{s}}{\\lambda_{o}}= \\frac{v\\pm v_{o}}{v\\mp v_{s}}",
    "Bernoulli's Equation": "P_{1} + \\varrho gy_{1} + \\frac{1}{2} \\varrho v_{1}^{2} = P_{2} + \\varrho gy_{2} + \\frac{1}{2} \\varrho v_{2}^{2}",
    "Relation between \\(K_p\\) and \\(K_c\\)": "K_p = K_c(RT)^{\\Delta n}",
    "Van der Waals Equation": "\\left (P + a \\frac{n^2}{V^2} \\right ) ( V - nb) = nRT",
    "Maxwell-Boltzmann Distribution": "f(v) = 4 \\pi v^2 \\left ( \\frac {m}{2 \\pi k T} \\right )^{3/2} e^{-\\frac{mv^2}{2k_BT}}",
    "Cayley-Hamilton Theorem": "p(\\lambda) = \\det (\\lambda \\mathbf{I}_n - \\mathbf{A}) \\implies p(\\mathbf{A}) = 0",
    "Chudnovsky's Formula for \\(\\pi\\)": "\\frac{1}{\\pi} = 12 \\sum^\\infty_{k=0} \\frac{(-1)^k (6k)! (545140134k + 13591409)}{(3k)!(k!)^3 (640320)^{3k + 3/2}}",
    "Residue Theorem": "\\frac{1}{2\\pi i}\\oint_\\gamma f(z)\\mathrm{d}z=\\sum_{p\\text{ pole}}\\mathbf{I}(\\gamma,p)\\mathrm{Res}(f,p)",
    "Center of Mass": "\\mathbf{R} = \\frac 1M \\iiint_Q \\rho(\\mathbf{r}) \\mathbf{r} \\mathrm dV",
    "The Fundamental Group of the Circle": "\\pi_1(S^1) \\cong \\mathbb{Z}",
    "Definition of the Operator Norm on a Finite Dimensional Banach Space.": "\\left \\{ \\frac{\\| T(x) \\|'}{\\| x \\|} : x \\neq 0, x \\in X \\right \\} \\equiv \\left \\{ \\| T(x) \\|' : \\| x \\| = 1,  x \\in X \\right\\}",
    "Green's Theorem": "\\oint_C (L \\mathrm dx +M \\mathrm  dy)=\\iint_D \\left(\\frac{\\partial M}{\\partial x}-\\frac{\\partial L}{\\partial y} \\right) \\mathrm dx \\mathrm dy",
    "Portfolio Variance": "\\sigma^2_z = \\left (\\sum_{i=1}^n w^2_i  \\sigma^2_i \\right )+ 2 \\left ( \\sum_{i=1}^{n-1}\\sum_{j = i+1}^n w_i w_j \\sigma_{i, j} \\right )",
    "Newton's Method": "x_{n+1} = x_n - \\frac{f(x_n)}{f'(x_n)}",
    "Shannon Entropy": "H(X) = -\\sum_{i=1}^n P(x_i) \\log_2 P(x_i)",
    "Pinsker's inequality": "\\|\\mu - \\nu\\|_{\\mathrm{ TV}} \\le \\sqrt{2 D_{\\rm KL}(\\mu\\|\\nu)}",
    "Sackur-Tetrode equation": "\\frac{S}{k_BN} = \\ln\\left[ \\frac VN \\left( \\frac{4\\pi m}{3h^2} \\frac UN \\right)^{3/2} \\right] + \\frac52",
    "Condtional Entropy": "\\mathrm H (Y|X)=-\\sum_{x \\in \\mathcal X, y \\in \\mathcal Y}p(x,y)\\log{\\frac{p(x,y)}{p(x)}}",
    "Force-Potential Relation": "\\mathbf F=-\\frac{\\partial U}{\\partial x}\\hat{\\mathbf i}-\\frac{\\partial U}{\\partial y}\\hat{\\mathbf j}-\\frac{\\partial U}{\\partial z}\\hat{\\mathbf k}=-\\vec\\nabla(U)",
    "Beta Function": "B(x,y)=\\int_{0}^{1}t^{x-1}(1-t)^{y-1} \\mathrm{d}t",
    "Moist Adiabatic Lapse Rate": "\\Gamma_{\\mathrm{w}} = -\\frac{\\mathrm{d}T}{\\mathrm{d}z} = g\\frac{\\left(1 + \\frac{H_{\\mathrm{v}} r}{R_{\\mathrm{sd}} T}\\right)}{\\left(c_{\\mathrm{pd}} + \\frac{H_{\\mathrm{v}}^2 r}{R_{\\mathrm{sw}} T^2}\\right)}",
    "Cardano's Formula": "\\sqrt[3]{-\\frac{q}{2} + \\sqrt{\\frac{q^{2}}{4} + \\frac{p^{3}}{27}}} + \\sqrt[3]{-\\frac{q}{2} - \\sqrt{\\frac{q^{2}}{4} + \\frac{p^{3}}{27}}}",
    "General Cubic Formula": "C = \\sqrt[3]{\\frac{\\Delta_{1} \\pm \\sqrt{\\Delta_{1}^{2} - 4\\Delta_{0}^{3}}}{2}}",
    "Riemann Zeta Function": "\\zeta(s)=\\frac1{\\Gamma (s)}\\int_0^\\infty\\frac{x^{s-1}}{e^x-1}\\mathrm dx",
    "Tangent Sum of Angles Formula": "\\tan(\\alpha \\pm \\beta) = \\frac{\\tan(\\alpha) \\pm \\tan(\\beta)}{1 \\mp \\tan(\\alpha)\\tan(\\beta)}",
    "Inner Product of Continuous Complex Valued Functions": "\\langle f,g\\rangle=\\int_{0}^{2\\pi}f(t)\\overline{g(t)}\\mathrm{d}t",
    "Definition of a Psuedorandom Generator": "\\left | \\Pr_{x \\leftarrow \\{0,1\\}^k} [\\mathcal A (G(x)) = 1] - \\Pr_{x \\leftarrow \\{0,1\\}^{p(k)}} [\\mathcal A (x) = 1]\\right | < \\mu(k)",
    "Generalized Stokes' theorem": "\\int_{\\partial M} \\omega = \\int_M \\mathrm{d} \\omega",
    "Cartan's magic formula": "\\mathcal{L}_X = \\mathrm{d} \\circ \\iota_X + \\iota_X \\circ \\mathrm{d}",
    "Ridge Regression": "\\ell(\\mathbf{w}) = \\frac{1}{N} \\| \\mathbf{Xw} - \\mathbf{y} \\|_2^2 + \\lambda \\|\\mathbf{w}\\|_2^2",
    "Evidence Lower Bound (ELBO)": "L(\\phi,\\theta;x) = \\mathbb{E}_{z \\sim q_\\phi\\left(\\cdot\\mid x\\right)} \\left[ \\ln\\frac{p_\\theta(x,z)}{q_\\phi(z\\mid x)} \\right]",
    "Langevin Dynamics (Overdamped)": "\\mathrm{d}x_t = -\\nabla U(x_t) \\mathrm{d}t + \\sqrt{2\\beta^{-1}} \\mathrm{d}W_t"
};